logger_node:
 rosSleepTime: 0.01

vicon_logger:
 buffSize: 10000
 outFileName: "viconOutput"
 topicName: "vicon/CAR/CAR"
 rosSubQueueSize: 1
 header: "t, x, y, z, angX, angY, angZ, qx, qy, qz, qw" 
	
imu_logger:
 buffSize: 10000
 outFileName: imuOutput
 topicName: imu/data
 rosSubQueueSize: 1
 header: "t, a_x, a_y, a_z, w_x, w_y, w_z, qx, qy, qz, qw"
		
enc_logger:
 buffSize: 10000
 outFileName: encOutput
 topicName: forward_vel
 rosSubQueueSize: 1
 header: "time, velFL, velFR, velBL, velBR" 